export type Bootcamp = {
  slug: string;
  nameBn: string;
  nameEn: string;
  taglineBn: string;
  taglineEn: string;
  durationMonths: number;
  priceBdt: number;
  emiMonthly: number;
  hours: number;
  liveClasses: number;
  projects: number;
  placement: number;
  iconKey: string;
  heroImage: string;
  description: string;
  outcomes: string[];
  curriculum: { month: number; title: string; topics: string[]; projects: string[] }[];
  schedule: { day: string; activity: string; time: string }[];
  tools: string[];
  nextBatchDate: string;
  seatsTotal: number;
  seatsRemaining: number;
};

export const BOOTCAMPS: Bootcamp[] = [
  {
    slug: "full-stack-web",
    nameBn: "ফুল-স্ট্যাক ওয়েব ডেভেলপমেন্ট",
    nameEn: "Full-Stack Web Development",
    taglineBn: "৬ মাসে হয়ে উঠুন প্রফেশনাল ডেভেলপার",
    taglineEn: "Become a professional developer in 6 months",
    durationMonths: 6,
    priceBdt: 45000,
    emiMonthly: 7500,
    hours: 320,
    liveClasses: 220,
    projects: 42,
    placement: 97,
    iconKey: "code",
    heroImage:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1600&q=80",
    description:
      "Industry-grade full-stack training with React, Node.js, and MongoDB. Build production-ready apps and crack interviews at top BD companies.",
    outcomes: [
      "Build full-stack web applications",
      "Master React, Node.js, MongoDB",
      "Deploy to production with CI/CD",
      "Crack technical interviews at top companies",
      "Earn ৳60,000–1,20,000 as junior developer",
      "Or freelance internationally on Upwork",
    ],
    curriculum: [
      {
        month: 1,
        title: "Web Fundamentals",
        topics: ["HTML5 semantics", "CSS3 + Flexbox + Grid", "JavaScript ES6+", "Git & GitHub", "Responsive design", "Browser dev tools"],
        projects: ["Personal portfolio site", "CSS landing page clone"],
      },
      {
        month: 2,
        title: "Frontend with React",
        topics: ["React fundamentals", "Hooks deep dive", "State management", "React Router", "Tailwind CSS", "API integration"],
        projects: ["Movie database app", "E-commerce frontend"],
      },
      {
        month: 3,
        title: "Backend with Node.js",
        topics: ["Node.js & Express", "REST API design", "MongoDB & Mongoose", "Authentication & JWT", "Error handling", "Testing with Jest"],
        projects: ["RESTful blog API", "Auth service"],
      },
      {
        month: 4,
        title: "Full-Stack Integration",
        topics: ["Next.js App Router", "TypeScript", "Server components", "Prisma ORM", "PostgreSQL", "Stripe payments"],
        projects: ["Full-stack SaaS clone", "E-commerce platform"],
      },
      {
        month: 5,
        title: "DevOps & Deployment",
        topics: ["Docker basics", "AWS EC2 & S3", "CI/CD with GitHub Actions", "Vercel deployment", "Performance & SEO", "Monitoring"],
        projects: ["Dockerized app deployment", "CI/CD pipeline"],
      },
      {
        month: 6,
        title: "Capstone & Career",
        topics: ["System design basics", "DSA for interviews", "Mock interviews", "Resume building", "LinkedIn optimization", "Freelance setup"],
        projects: ["Capstone project (4 weeks)", "Open-source contribution"],
      },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "লাইভ ক্লাস + মেন্টর সেশন", time: "৭:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "লাইভ ক্লাস + প্রজেক্ট", time: "৭:০০ – ১০:০০ PM" },
      { day: "বুধবার", activity: "Catch-up day (Off)", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "শনিবার", activity: "প্রজেক্ট ডেমো + কমিউনিটি", time: "৩:০০ – ৬:০০ PM" },
    ],
    tools: ["HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Next.js", "Node.js", "Express", "MongoDB", "PostgreSQL", "Tailwind", "Git", "Docker", "AWS"],
    nextBatchDate: "2026-06-15",
    seatsTotal: 45,
    seatsRemaining: 12,
  },
  {
    slug: "data-science-ai",
    nameBn: "ডেটা সায়েন্স ও AI",
    nameEn: "Data Science & AI",
    taglineBn: "ডেটা থেকে ইনসাইট, ইনসাইট থেকে ক্যারিয়ার",
    taglineEn: "From data to insights, insights to career",
    durationMonths: 6,
    priceBdt: 50000,
    emiMonthly: 8500,
    hours: 350,
    liveClasses: 230,
    projects: 38,
    placement: 95,
    iconKey: "brain",
    heroImage:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80",
    description:
      "Master Python, statistics, ML, and modern AI. Build a portfolio that lands data roles at Pathao, bKash, Brain Station 23.",
    outcomes: [
      "Master Python and data analysis",
      "Build ML & deep learning models",
      "Work with LLMs and modern AI",
      "Crack data science interviews",
      "Earn ৳70,000–1,50,000 as data scientist",
      "Build production ML pipelines",
    ],
    curriculum: [
      { month: 1, title: "Python & Statistics", topics: ["Python deep dive", "NumPy & Pandas", "Statistics fundamentals", "EDA techniques"], projects: ["Sales analysis dashboard"] },
      { month: 2, title: "SQL & Data Engineering", topics: ["SQL mastery", "Data cleaning", "ETL pipelines", "Data warehousing"], projects: ["BD telecom data pipeline"] },
      { month: 3, title: "Machine Learning", topics: ["Scikit-learn", "Regression & classification", "Tree models", "Model evaluation"], projects: ["Loan prediction model"] },
      { month: 4, title: "Deep Learning", topics: ["Neural networks", "CNN for images", "RNN/LSTM for text", "Transfer learning"], projects: ["Bangla OCR model"] },
      { month: 5, title: "LLMs & GenAI", topics: ["Transformers", "Hugging Face", "RAG systems", "Fine-tuning"], projects: ["Bangla chatbot"] },
      { month: 6, title: "MLOps & Career", topics: ["Model deployment", "MLflow & Docker", "Interview prep", "Capstone"], projects: ["End-to-end ML system"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "লাইভ ক্লাস + ল্যাব", time: "৭:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "মেন্টর সেশন", time: "৮:০০ – ১০:০০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "প্রজেক্ট রিভিউ", time: "৭:০০ – ১০:০০ PM" },
      { day: "শনিবার", activity: "Kaggle competition", time: "৩:০০ – ৬:০০ PM" },
    ],
    tools: ["Python", "Pandas", "NumPy", "Scikit-learn", "TensorFlow", "PyTorch", "Hugging Face", "SQL", "Docker", "AWS", "MLflow"],
    nextBatchDate: "2026-06-20",
    seatsTotal: 40,
    seatsRemaining: 8,
  },
  {
    slug: "digital-marketing",
    nameBn: "ডিজিটাল মার্কেটিং প্রো",
    nameEn: "Digital Marketing Pro",
    taglineBn: "ব্র্যান্ড থেকে রেভিনিউ — ৪ মাসে",
    taglineEn: "From brand to revenue — in 4 months",
    durationMonths: 4,
    priceBdt: 25000,
    emiMonthly: 6500,
    hours: 200,
    liveClasses: 140,
    projects: 24,
    placement: 96,
    iconKey: "megaphone",
    heroImage:
      "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1600&q=80",
    description: "Performance marketing, SEO, social media, content, analytics — build a marketer's portfolio agencies want.",
    outcomes: [
      "Run profitable Facebook & Google ads",
      "Rank websites on Google",
      "Build content & social strategies",
      "Analyze with GA4",
      "Land jobs at top BD agencies",
      "Or freelance internationally",
    ],
    curriculum: [
      { month: 1, title: "Marketing Foundations", topics: ["Marketing strategy", "Buyer personas", "Brand basics", "Funnel design"], projects: ["Brand strategy doc"] },
      { month: 2, title: "Paid Ads", topics: ["Facebook Ads Manager", "Google Ads", "TikTok Ads", "Conversion tracking"], projects: ["Live ad campaign"] },
      { month: 3, title: "SEO & Content", topics: ["On-page SEO", "Link building", "Content strategy", "Email marketing"], projects: ["SEO audit + plan"] },
      { month: 4, title: "Analytics & Career", topics: ["GA4 mastery", "Reporting", "Agency workflow", "Portfolio"], projects: ["Capstone client work"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "প্র্যাকটিক্যাল", time: "৮:০০ – ১০:০০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "Mentor", time: "৮:০০ – ৯:৩০ PM" },
      { day: "শনিবার", activity: "Project review", time: "৪:০০ – ৬:০০ PM" },
    ],
    tools: ["Facebook Ads", "Google Ads", "GA4", "SEMrush", "Ahrefs", "Mailchimp", "Canva", "Meta Business Suite"],
    nextBatchDate: "2026-06-10",
    seatsTotal: 50,
    seatsRemaining: 22,
  },
  {
    slug: "ui-ux-design",
    nameBn: "UI/UX ডিজাইন",
    nameEn: "UI/UX Design",
    taglineBn: "প্রোডাক্ট ডিজাইনার হয়ে উঠুন",
    taglineEn: "Become a product designer",
    durationMonths: 4,
    priceBdt: 30000,
    emiMonthly: 7000,
    hours: 220,
    liveClasses: 150,
    projects: 26,
    placement: 94,
    iconKey: "pen-tool",
    heroImage:
      "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=1600&q=80",
    description: "User research to high-fidelity Figma prototypes. Build a portfolio that gets shortlisted at product companies.",
    outcomes: [
      "Master Figma & Figma plugins",
      "Run user research & usability tests",
      "Design systems from scratch",
      "Build a 5-piece portfolio",
      "Land UI/UX roles at top BD startups",
      "Freelance on Toptal / Dribbble",
    ],
    curriculum: [
      { month: 1, title: "Design Foundations", topics: ["Visual design", "Typography", "Color theory", "Layout principles"], projects: ["Visual exploration"] },
      { month: 2, title: "UX Research", topics: ["User interviews", "Personas", "Journey maps", "Wireframing"], projects: ["UX case study"] },
      { month: 3, title: "UI Mastery", topics: ["Figma deep dive", "Components", "Auto-layout", "Design systems"], projects: ["Complete app design"] },
      { month: 4, title: "Portfolio & Career", topics: ["Case study writing", "Portfolio site", "Interviews", "Freelancing"], projects: ["Personal portfolio"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "Mentor critique", time: "৮:০০ – ৯:৩০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "Design review", time: "৮:০০ – ১০:০০ PM" },
      { day: "শনিবার", activity: "Studio time", time: "৩:০০ – ৬:০০ PM" },
    ],
    tools: ["Figma", "FigJam", "Adobe XD", "Photoshop", "Illustrator", "Maze", "Notion", "Framer"],
    nextBatchDate: "2026-06-25",
    seatsTotal: 35,
    seatsRemaining: 9,
  },
  {
    slug: "graphic-design",
    nameBn: "গ্রাফিক ডিজাইন কমপ্লিট",
    nameEn: "Graphic Design Complete",
    taglineBn: "তিন মাসে প্রফেশনাল ডিজাইনার",
    taglineEn: "Professional designer in 3 months",
    durationMonths: 3,
    priceBdt: 20000,
    emiMonthly: 7000,
    hours: 160,
    liveClasses: 110,
    projects: 30,
    placement: 92,
    iconKey: "image",
    heroImage:
      "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1600&q=80",
    description: "Photoshop, Illustrator, branding, social design — build a freelance career or land an agency seat.",
    outcomes: [
      "Master Adobe Creative Cloud",
      "Build brand identities",
      "Design social campaigns",
      "Print & packaging design",
      "Freelance internationally on Fiverr",
      "Or join top BD agencies",
    ],
    curriculum: [
      { month: 1, title: "Tools mastery", topics: ["Photoshop", "Illustrator", "Color & typography"], projects: ["10 social posts"] },
      { month: 2, title: "Branding", topics: ["Logo design", "Brand systems", "Print design"], projects: ["Full brand identity"] },
      { month: 3, title: "Career & Freelance", topics: ["Portfolio", "Fiverr setup", "Client comms"], projects: ["Freelance ready portfolio"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "Studio", time: "৮:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "Critique", time: "৮:০০ – ৯:৩০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "শনিবার", activity: "Showcase", time: "৪:০০ – ৬:০০ PM" },
    ],
    tools: ["Photoshop", "Illustrator", "InDesign", "Figma", "Canva Pro", "Affinity"],
    nextBatchDate: "2026-06-05",
    seatsTotal: 40,
    seatsRemaining: 18,
  },
  {
    slug: "video-editing",
    nameBn: "ভিডিও এডিটিং ও মোশন গ্রাফিক্স",
    nameEn: "Video Editing & Motion Graphics",
    taglineBn: "ক্যামেরার পেছন থেকে ক্যারিয়ারে",
    taglineEn: "From behind the camera to a career",
    durationMonths: 3,
    priceBdt: 20000,
    emiMonthly: 7000,
    hours: 170,
    liveClasses: 115,
    projects: 28,
    placement: 90,
    iconKey: "film",
    heroImage:
      "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1600&q=80",
    description: "Premiere Pro, After Effects, color, sound — be the editor brands and YouTubers fight to hire.",
    outcomes: [
      "Master Premiere Pro & After Effects",
      "Color grading workflows",
      "Motion graphics & VFX",
      "Sound design",
      "YouTube editor skills",
      "Freelance for global creators",
    ],
    curriculum: [
      { month: 1, title: "Editing", topics: ["Premiere Pro", "Cutting", "Pacing", "Music"], projects: ["3 short reels"] },
      { month: 2, title: "Motion Graphics", topics: ["After Effects", "Animation principles", "Logo reveals"], projects: ["Brand intro pack"] },
      { month: 3, title: "Color & Audio", topics: ["DaVinci Resolve", "Audio mixing", "Color grading", "Career"], projects: ["Cinematic short"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "Studio time", time: "৮:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "Mentor", time: "৮:০০ – ৯:৩০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "শনিবার", activity: "Showcase", time: "৪:০০ – ৬:০০ PM" },
    ],
    tools: ["Premiere Pro", "After Effects", "DaVinci Resolve", "Audition", "Photoshop", "CapCut"],
    nextBatchDate: "2026-06-12",
    seatsTotal: 35,
    seatsRemaining: 14,
  },
  {
    slug: "freelancing-master",
    nameBn: "ফ্রিল্যান্সিং মাস্টারক্লাস",
    nameEn: "Freelancing Masterclass",
    taglineBn: "বিশ্ববাজারে ডলার আয় শুরু করুন",
    taglineEn: "Start earning USD on the world market",
    durationMonths: 3,
    priceBdt: 15000,
    emiMonthly: 5500,
    hours: 130,
    liveClasses: 90,
    projects: 18,
    placement: 88,
    iconKey: "globe",
    heroImage:
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1600&q=80",
    description: "Upwork, Fiverr, LinkedIn — get clients, win contracts, deliver value, scale your freelance income.",
    outcomes: [
      "Set up winning Upwork & Fiverr profiles",
      "Pitch to international clients",
      "Negotiate USD rates",
      "Use Payoneer & Wise",
      "Build a $1000/month income",
      "Scale to agency model",
    ],
    curriculum: [
      { month: 1, title: "Foundations", topics: ["Niching", "Profile building", "Portfolio", "Pricing"], projects: ["Optimized Upwork profile"] },
      { month: 2, title: "Client acquisition", topics: ["Cold pitching", "Proposals", "LinkedIn outreach"], projects: ["First paid client"] },
      { month: 3, title: "Scale & systems", topics: ["Retention", "Contracts", "Tax/banking", "Agency scale"], projects: ["Recurring client setup"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৯:০০ – ১১:০০ PM" },
      { day: "সোমবার", activity: "Office hour", time: "৯:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "Mentor", time: "৯:০০ – ১০:৩০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৯:০০ – ১১:০০ PM" },
      { day: "শুক্রবার", activity: "Pitch day", time: "৯:০০ – ১১:০০ PM" },
      { day: "শনিবার", activity: "Community", time: "৪:০০ – ৬:০০ PM" },
    ],
    tools: ["Upwork", "Fiverr", "LinkedIn", "Payoneer", "Wise", "Notion", "Calendly", "Loom"],
    nextBatchDate: "2026-06-08",
    seatsTotal: 60,
    seatsRemaining: 28,
  },
  {
    slug: "product-management",
    nameBn: "প্রোডাক্ট ম্যানেজমেন্ট",
    nameEn: "Product Management",
    taglineBn: "টেক প্রোডাক্ট ম্যানেজার হয়ে উঠুন",
    taglineEn: "Become a tech product manager",
    durationMonths: 4,
    priceBdt: 35000,
    emiMonthly: 7500,
    hours: 240,
    liveClasses: 160,
    projects: 22,
    placement: 93,
    iconKey: "compass",
    heroImage:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1600&q=80",
    description: "Discovery, roadmaps, metrics, leadership — make the leap into product at top BD tech companies.",
    outcomes: [
      "Run product discovery",
      "Write PRDs & user stories",
      "Master analytics & A/B testing",
      "Roadmap & prioritization",
      "Land PM roles at top BD startups",
      "Lead cross-functional teams",
    ],
    curriculum: [
      { month: 1, title: "PM foundations", topics: ["What is PM", "Discovery", "Customer research"], projects: ["Discovery report"] },
      { month: 2, title: "Strategy & Roadmaps", topics: ["Frameworks", "Prioritization", "PRDs"], projects: ["Full PRD"] },
      { month: 3, title: "Execution", topics: ["Agile", "Metrics", "A/B testing"], projects: ["Experiment plan"] },
      { month: 4, title: "Leadership & Career", topics: ["Stakeholders", "Vision", "Interviews"], projects: ["PM portfolio"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "Mentor", time: "৮:০০ – ৯:৩০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "Case study", time: "৮:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "Mock interview", time: "৮:০০ – ১০:০০ PM" },
      { day: "শনিবার", activity: "Workshop", time: "৩:০০ – ৬:০০ PM" },
    ],
    tools: ["Jira", "Confluence", "Notion", "Figma", "Mixpanel", "Amplitude", "Optimizely", "SQL"],
    nextBatchDate: "2026-06-22",
    seatsTotal: 30,
    seatsRemaining: 6,
  },
  {
    slug: "mobile-app",
    nameBn: "মোবাইল অ্যাপ ডেভেলপমেন্ট",
    nameEn: "Mobile App Development",
    taglineBn: "iOS + Android — একসাথে শিখুন",
    taglineEn: "iOS + Android — learn together",
    durationMonths: 5,
    priceBdt: 40000,
    emiMonthly: 7500,
    hours: 290,
    liveClasses: 200,
    projects: 32,
    placement: 92,
    iconKey: "smartphone",
    heroImage:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1600&q=80",
    description: "React Native + Flutter cross-platform mastery. Ship apps to App Store & Play Store and crack interviews.",
    outcomes: [
      "Master React Native & Flutter",
      "Publish to App Store + Play Store",
      "Native modules and bridges",
      "Push notifications & analytics",
      "Land mobile dev roles at Pathao, bKash",
      "Or freelance for international clients",
    ],
    curriculum: [
      { month: 1, title: "JS & Dart foundations", topics: ["JS deep dive", "Dart basics", "Mobile principles"], projects: ["Hello-World apps"] },
      { month: 2, title: "React Native", topics: ["RN core", "Navigation", "State", "API"], projects: ["Weather app"] },
      { month: 3, title: "Flutter", topics: ["Widgets", "State", "Firebase"], projects: ["Chat app"] },
      { month: 4, title: "Production", topics: ["Push notifications", "Analytics", "Performance", "Native modules"], projects: ["Production-ready app"] },
      { month: 5, title: "Publishing & Career", topics: ["App Store + Play Store", "ASO", "Interviews"], projects: ["Published app"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "Mentor + project", time: "৭:০০ – ১০:০০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "লাইভ ক্লাস", time: "৭:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "Code review", time: "৭:০০ – ১০:০০ PM" },
      { day: "শনিবার", activity: "Demo day", time: "৩:০০ – ৬:০০ PM" },
    ],
    tools: ["React Native", "Flutter", "Dart", "TypeScript", "Firebase", "Xcode", "Android Studio", "Expo"],
    nextBatchDate: "2026-06-18",
    seatsTotal: 35,
    seatsRemaining: 11,
  },
  {
    slug: "ecommerce-entrepreneurship",
    nameBn: "ই-কমার্স এন্ট্রেপ্রেনারশিপ",
    nameEn: "E-commerce Entrepreneurship",
    taglineBn: "নিজের অনলাইন ব্যবসা শুরু করুন",
    taglineEn: "Start your own online business",
    durationMonths: 3,
    priceBdt: 18000,
    emiMonthly: 6500,
    hours: 140,
    liveClasses: 95,
    projects: 16,
    placement: 85,
    iconKey: "shopping-bag",
    heroImage:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1600&q=80",
    description: "Daraz, Facebook commerce, Shopify — build a profitable BD e-commerce business from scratch.",
    outcomes: [
      "Validate product ideas",
      "Set up Daraz & Facebook commerce",
      "Build a Shopify store",
      "Run profitable ads",
      "Manage logistics & customer service",
      "Scale to ৳2L+ monthly revenue",
    ],
    curriculum: [
      { month: 1, title: "Niche & sourcing", topics: ["Market research", "China/local sourcing", "Product validation"], projects: ["Product launch plan"] },
      { month: 2, title: "Stores & ads", topics: ["Daraz seller setup", "Shopify", "Facebook commerce", "Ads"], projects: ["Live store"] },
      { month: 3, title: "Scale & ops", topics: ["Logistics", "Customer service", "Finance", "Tax"], projects: ["First 100 sales"] },
    ],
    schedule: [
      { day: "রবিবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "সোমবার", activity: "লাইভ ক্লাস", time: "৮:০০ – ১০:০০ PM" },
      { day: "মঙ্গলবার", activity: "Mentor", time: "৮:০০ – ৯:৩০ PM" },
      { day: "বুধবার", activity: "Off", time: "—" },
      { day: "বৃহস্পতিবার", activity: "Live workshop", time: "৮:০০ – ১০:০০ PM" },
      { day: "শুক্রবার", activity: "Office hour", time: "৮:০০ – ৯:৩০ PM" },
      { day: "শনিবার", activity: "Showcase", time: "৪:০০ – ৬:০০ PM" },
    ],
    tools: ["Shopify", "Daraz Seller Center", "Facebook Commerce", "Meta Ads", "Canva", "Google Sheets", "WhatsApp Business"],
    nextBatchDate: "2026-06-04",
    seatsTotal: 50,
    seatsRemaining: 24,
  },
];

export type Mentor = {
  slug: string;
  nameBn: string;
  nameEn: string;
  designation: string;
  company: string;
  companyLogo: string;
  photo: string;
  yearsExp: number;
  bio: string;
  expertise: string[];
  tracks: string[];
  linkedin?: string;
};

export const MENTORS: Mentor[] = [
  {
    slug: "rakib-hasan",
    nameBn: "রাকিব হাসান",
    nameEn: "Rakib Hasan",
    designation: "Senior Software Engineer",
    company: "Pathao",
    companyLogo: "https://logo.clearbit.com/pathao.com",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    yearsExp: 9,
    bio: "Pathao-এ ৯ বছরের সফটওয়্যার ইঞ্জিনিয়ারিং অভিজ্ঞতা। React, Node.js, এবং স্কেলেবল আর্কিটেকচারে স্পেশালিস্ট।",
    expertise: ["React", "Node.js", "AWS", "System design"],
    tracks: ["full-stack-web", "mobile-app"],
    linkedin: "https://linkedin.com/in/rakibhasan",
  },
  {
    slug: "tasneem-akter",
    nameBn: "তাসনিম আক্তার",
    nameEn: "Tasneem Akter",
    designation: "Lead Data Scientist",
    company: "bKash",
    companyLogo: "https://logo.clearbit.com/bkash.com",
    photo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=80",
    yearsExp: 7,
    bio: "bKash-এ ফিনটেক ডেটা সায়েন্স লিড। ফ্রড ডিটেকশন এবং ক্রেডিট স্কোরিং মডেলে বিশেষজ্ঞ।",
    expertise: ["ML", "Deep learning", "MLOps", "Bangla NLP"],
    tracks: ["data-science-ai"],
    linkedin: "https://linkedin.com/in/tasneemakter",
  },
  {
    slug: "saif-rahman",
    nameBn: "সাইফ রহমান",
    nameEn: "Saif Rahman",
    designation: "Product Manager",
    company: "Brain Station 23",
    companyLogo: "https://logo.clearbit.com/brainstation-23.com",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80",
    yearsExp: 8,
    bio: "৮ বছর ধরে B2B SaaS প্রোডাক্ট ম্যানেজমেন্ট। বাংলাদেশ এবং ইউরোপের জন্য প্রোডাক্ট লিড করেছেন।",
    expertise: ["Product strategy", "Discovery", "Roadmaps", "Analytics"],
    tracks: ["product-management"],
    linkedin: "https://linkedin.com/in/saifrahman",
  },
  {
    slug: "naima-chowdhury",
    nameBn: "নাইমা চৌধুরী",
    nameEn: "Naima Chowdhury",
    designation: "Senior UX Designer",
    company: "Therap Services",
    companyLogo: "https://logo.clearbit.com/therapservices.net",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&q=80",
    yearsExp: 6,
    bio: "Healthcare প্রোডাক্ট ডিজাইনে ৬ বছরের অভিজ্ঞতা। US ভিত্তিক বড় টিমের সাথে কাজ করেছেন।",
    expertise: ["UX research", "Figma", "Design systems", "Accessibility"],
    tracks: ["ui-ux-design"],
    linkedin: "https://linkedin.com/in/naimachowdhury",
  },
  {
    slug: "imran-khan",
    nameBn: "ইমরান খান",
    nameEn: "Imran Khan",
    designation: "Performance Marketing Lead",
    company: "Daraz",
    companyLogo: "https://logo.clearbit.com/daraz.com",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80",
    yearsExp: 7,
    bio: "Daraz-এ গ্রোথ মার্কেটিং লিড। ৭ বছরে ৳১০০ কোটি+ ad spend অপ্টিমাইজ করেছেন।",
    expertise: ["Facebook Ads", "Google Ads", "Growth", "Analytics"],
    tracks: ["digital-marketing"],
    linkedin: "https://linkedin.com/in/imrankhan",
  },
  {
    slug: "zahid-iqbal",
    nameBn: "জাহিদ ইকবাল",
    nameEn: "Zahid Iqbal",
    designation: "Mobile Engineering Lead",
    company: "Tiger IT",
    companyLogo: "https://logo.clearbit.com/tigerit.com",
    photo: "https://images.unsplash.com/photo-1557862921-37829c790f19?w=600&q=80",
    yearsExp: 10,
    bio: "১০ বছরের মোবাইল ডেভেলপমেন্ট অভিজ্ঞতা। React Native এবং Flutter এ এন্টারপ্রাইজ প্রোডাক্ট শিপ করেছেন।",
    expertise: ["React Native", "Flutter", "iOS", "Android"],
    tracks: ["mobile-app", "full-stack-web"],
    linkedin: "https://linkedin.com/in/zahidiqbal",
  },
  {
    slug: "fariha-binte",
    nameBn: "ফারিহা বিনতে",
    nameEn: "Fariha Binte",
    designation: "Creative Director",
    company: "Asiatic 360",
    companyLogo: "https://logo.clearbit.com/asiatic360.com",
    photo: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80",
    yearsExp: 9,
    bio: "Top BD agency-তে ক্রিয়েটিভ ডিরেকটর। Unilever, Grameenphone, BRAC-এর জন্য ব্র্যান্ড ক্যাম্পেইন।",
    expertise: ["Branding", "Art direction", "Photoshop", "Illustrator"],
    tracks: ["graphic-design", "ui-ux-design"],
    linkedin: "https://linkedin.com/in/farihabinte",
  },
  {
    slug: "shahriar-mahmud",
    nameBn: "শাহরিয়ার মাহমুদ",
    nameEn: "Shahriar Mahmud",
    designation: "Founder & CEO",
    company: "PixelCraft",
    companyLogo: "https://logo.clearbit.com/pixelcraftbd.com",
    photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&q=80",
    yearsExp: 11,
    bio: "ভিডিও এডিটিং এজেন্সি ফাউন্ডার। ১০০+ ব্র্যান্ডের জন্য কন্টেন্ট প্রোডাকশন।",
    expertise: ["Premiere Pro", "After Effects", "Color grading", "Direction"],
    tracks: ["video-editing"],
    linkedin: "https://linkedin.com/in/shahriarmahmud",
  },
];

export type Alumni = {
  slug: string;
  nameBn: string;
  nameEn: string;
  photo: string;
  beforeRole: string;
  afterRole: string;
  company: string;
  companyLogo: string;
  salary: number;
  salaryGrowth: string;
  trackSlug: string;
  batch: string;
  quote: string;
  story: string;
  featured?: boolean;
};

export const ALUMNI: Alumni[] = [
  {
    slug: "mir-sakib",
    nameBn: "মীর সাকিব",
    nameEn: "Mir Sakib",
    photo: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800&q=80",
    beforeRole: "কুমিল্লার ছোট দোকানে চাকরিপ্রার্থী",
    afterRole: "Software Engineer",
    company: "Pathao",
    companyLogo: "https://logo.clearbit.com/pathao.com",
    salary: 120000,
    salaryGrowth: "৳০ → ৳১,২০,০০০",
    trackSlug: "full-stack-web",
    batch: "Batch 35",
    quote: "যাত্রা আমার জীবন বদলে দিয়েছে। ৬ মাস আগে আমি গ্রামের ছেলে — কোডিং কী জানতাম না। আজ আমি Pathao-তে Software Engineer। মাসিক বেতন ১,২০,০০০ টাকা।",
    story: "কুমিল্লার একটা ছোট গ্রামে বেড়ে উঠেছি। কম্পিউটার সায়েন্স পড়েছি ঠিকই, কিন্তু কোডিং প্র্যাকটিকাল কখনো করিনি। গ্র্যাজুয়েশনের পর ১৮ মাস বেকার ছিলাম। যাত্রার বুটক্যাম্প আমার জীবন পরিবর্তন করেছে। লাইভ ক্লাস, ১:১ মেন্টর, রিয়েল প্রজেক্ট — সবকিছুই অসাধারণ। ৫ মাসের মধ্যে Pathao-তে চাকরি পেলাম।",
    featured: true,
  },
  {
    slug: "rumana-akter",
    nameBn: "রুমানা আক্তার",
    nameEn: "Rumana Akter",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80",
    beforeRole: "Bank Operations Officer · ৳28,000",
    afterRole: "Data Scientist",
    company: "bKash",
    companyLogo: "https://logo.clearbit.com/bkash.com",
    salary: 95000,
    salaryGrowth: "3.4x",
    trackSlug: "data-science-ai",
    batch: "Batch 33",
    quote: "ব্যাংকের নয়টা-ছয়টা চাকরি ছেড়ে নতুন ক্যারিয়ার শুরু করার সাহস যাত্রা দিয়েছে।",
    story: "৫ বছর ব্যাংকে অপারেশনস অফিসার ছিলাম। বেতন বাড়েনি, কাজে বোরিং লাগছিল। যাত্রার ডেটা সায়েন্স ট্র্যাকে enroll করি। Career switch একদম মসৃণ ছিল।",
  },
  {
    slug: "tareq-aziz",
    nameBn: "তারেক আজিজ",
    nameEn: "Tareq Aziz",
    photo: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&q=80",
    beforeRole: "BBA গ্র্যাজুয়েট, বেকার",
    afterRole: "Product Manager",
    company: "Brain Station 23",
    companyLogo: "https://logo.clearbit.com/brainstation-23.com",
    salary: 85000,
    salaryGrowth: "৳০ → ৳৮৫,০০০",
    trackSlug: "product-management",
    batch: "Batch 36",
    quote: "Tech background ছাড়াও আমি PM হতে পেরেছি। যাত্রার মেন্টররা একদম industry insider।",
    story: "BBA করার পর ভাবতাম MBA করব। কিন্তু যাত্রার PM ট্র্যাকে গিয়ে বুঝলাম — tech-এ অনেক সুযোগ আছে। ৪ মাসের বুটক্যাম্প শেষে BS23-এ Associate PM পদে যোগ দিলাম।",
  },
  {
    slug: "nusrat-jahan",
    nameBn: "নুসরাত জাহান",
    nameEn: "Nusrat Jahan",
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80",
    beforeRole: "Stay-at-home parent",
    afterRole: "UI/UX Designer (Remote)",
    company: "Toptal",
    companyLogo: "https://logo.clearbit.com/toptal.com",
    salary: 130000,
    salaryGrowth: "৳০ → ৳১,৩০,০০০",
    trackSlug: "ui-ux-design",
    batch: "Batch 32",
    quote: "একজন মা হিসেবে remote কাজ আমার জন্য vital ছিল। যাত্রা আমাকে সেই path দিয়েছে।",
    story: "৮ বছর সংসার সামলে আবার ক্যারিয়ারে ফিরতে চেয়েছিলাম। Remote design work আমার জন্য perfect ছিল। যাত্রায় Figma শিখে Toptal-এ accept হয়েছি।",
  },
  {
    slug: "abdul-karim",
    nameBn: "আবদুল করিম",
    nameEn: "Abdul Karim",
    photo: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&q=80",
    beforeRole: "ছোট ব্যবসায়ী",
    afterRole: "E-commerce Owner · ৳3.5L/মাস",
    company: "নিজের ব্যবসা",
    companyLogo: "https://logo.clearbit.com/daraz.com",
    salary: 350000,
    salaryGrowth: "৳40,000 → ৳3,50,000",
    trackSlug: "ecommerce-entrepreneurship",
    batch: "Batch 38",
    quote: "Daraz এবং Facebook commerce — দুটো প্ল্যাটফর্মে এখন আমার ৬ জন employee।",
    story: "চট্টগ্রামে ছোট কাপড়ের দোকান ছিল। যাত্রায় E-commerce ট্র্যাকে enroll করে Daraz seller হলাম। ১ বছরে ৬ জনের টিম, ৩.৫ লাখ টাকা মাসিক revenue।",
  },
  {
    slug: "anika-tasnim",
    nameBn: "অনিকা তাসনিম",
    nameEn: "Anika Tasnim",
    photo: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=800&q=80",
    beforeRole: "Marketing intern",
    afterRole: "Performance Marketing Manager",
    company: "Foodpanda",
    companyLogo: "https://logo.clearbit.com/foodpanda.com",
    salary: 75000,
    salaryGrowth: "3x",
    trackSlug: "digital-marketing",
    batch: "Batch 34",
    quote: "Internship-এ ছিলাম, কিছুই শিখছিলাম না। যাত্রার ৪ মাসে আমার career rocket হয়ে গেছে।",
    story: "Foodpanda-তে এখন full-funnel marketing handle করি। ৳70K বেতন এবং performance bonus। ২৩ বছর বয়সে এই achievement যাত্রার জন্যই।",
  },
  {
    slug: "rifat-hossain",
    nameBn: "রিফাত হোসেন",
    nameEn: "Rifat Hossain",
    photo: "https://images.unsplash.com/photo-1639149888905-fb39731f2e6c?w=800&q=80",
    beforeRole: "Engineering student",
    afterRole: "Mobile Developer",
    company: "REVE Systems",
    companyLogo: "https://logo.clearbit.com/revesoft.com",
    salary: 70000,
    salaryGrowth: "Fresh grad",
    trackSlug: "mobile-app",
    batch: "Batch 37",
    quote: "ইউনিভার্সিটি শেষ হওয়ার আগেই যাত্রা শুরু করেছি। গ্র্যাজুয়েশনের ১ মাসের মধ্যে চাকরি।",
    story: "BUET-এর শেষ বছরে যাত্রার মোবাইল ট্র্যাকে যোগ দিলাম। React Native এবং Flutter mastery করে REVE-তে junior দেব হিসেবে যোগ দিলাম। বেতন ৭০K।",
  },
  {
    slug: "sadia-ahmed",
    nameBn: "সাদিয়া আহমেদ",
    nameEn: "Sadia Ahmed",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80",
    beforeRole: "Class 12 student",
    afterRole: "Freelance Designer · $2K/mo",
    company: "Fiverr Pro",
    companyLogo: "https://logo.clearbit.com/fiverr.com",
    salary: 220000,
    salaryGrowth: "৳০ → $2K/mo",
    trackSlug: "graphic-design",
    batch: "Batch 36",
    quote: "১৭ বছর বয়সে আমি গ্রাফিক ডিজাইনের freelance income শুরু করেছি।",
    story: "ক্লাস ১২-তে পড়ার সময় parents চাইতেন আমি ভর্তি কোচিং করি। কিন্তু আমি ডিজাইনের প্রতি passionate ছিলাম। যাত্রায় ৩ মাসের কোর্স শেষে Fiverr-এ Pro হয়েছি।",
  },
  {
    slug: "kawsar-ali",
    nameBn: "কাওসার আলী",
    nameEn: "Kawsar Ali",
    photo: "https://images.unsplash.com/photo-1543132220-3ec99c6094dc?w=800&q=80",
    beforeRole: "Madrasah teacher",
    afterRole: "Frontend Developer",
    company: "Banglalink",
    companyLogo: "https://logo.clearbit.com/banglalink.net",
    salary: 80000,
    salaryGrowth: "5x",
    trackSlug: "full-stack-web",
    batch: "Batch 33",
    quote: "৩৫ বছর বয়সে career switch করেছি। বয়স কখনো বাধা নয়।",
    story: "১০ বছর মাদ্রাসায় শিক্ষকতা করেছি। বেতন ছিল ১৬ হাজার টাকা। যাত্রায় enroll করে ৬ মাসে Banglalink-এ ৮০K বেতনে frontend dev হিসেবে join করেছি।",
  },
];

export type BlogPost = {
  slug: string;
  titleBn: string;
  titleEn: string;
  excerpt: string;
  cover: string;
  author: string;
  authorPhoto: string;
  category: string;
  readMin: number;
  body: string;
  publishedAt: string;
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "bd-developer-salary-2026",
    titleBn: "বাংলাদেশে ডেভেলপার বেতন গাইড ২০২৬",
    titleEn: "BD Developer Salary Guide 2026",
    excerpt: "জুনিয়র, মিড, সিনিয়র — তিন স্তরে বেতনের তথ্য। ২০২৬ সালের সর্বশেষ বাজার বিশ্লেষণ।",
    cover: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1600&q=80",
    author: "রাকিব হাসান",
    authorPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    category: "Industry insights",
    readMin: 8,
    body: "২০২৬ সালে বাংলাদেশের সফটওয়্যার ইন্ডাস্ট্রি অভূতপূর্ব বৃদ্ধি দেখেছে। জুনিয়র ডেভেলপারদের গড় বেতন ৪০-৭০ হাজার টাকা থেকে বেড়ে এখন ৫৫-৯০ হাজার টাকা। সিনিয়র লেভেলে ১.৫-৩ লাখ টাকা পর্যন্ত উঠেছে।",
    publishedAt: "2026-04-12",
  },
  {
    slug: "interview-prep-bd-tech",
    titleBn: "টপ ৫ বিডি টেক ইন্টারভিউ প্রশ্ন",
    titleEn: "Top 5 BD Tech Interview Questions",
    excerpt: "Pathao, bKash, Brain Station 23 ইন্টারভিউয়ে যেসব প্রশ্ন বার বার আসে।",
    cover: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1600&q=80",
    author: "তাসনিম আক্তার",
    authorPhoto: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&q=80",
    category: "Career advice",
    readMin: 6,
    body: "যাত্রার মেন্টররা ১৫০+ স্টুডেন্টের ইন্টারভিউ প্রিপারেশন করিয়েছেন। তাদের অভিজ্ঞতা থেকে এই প্রশ্নগুলো সবচেয়ে বেশি আসে।",
    publishedAt: "2026-04-05",
  },
  {
    slug: "bootcamp-vs-degree",
    titleBn: "বুটক্যাম্প বনাম ইউনিভার্সিটি ডিগ্রি",
    titleEn: "Bootcamp vs University Degree",
    excerpt: "তিন বছরের ডিগ্রি, নাকি ছয় মাসের বুটক্যাম্প — কোনটা ভালো?",
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1600&q=80",
    author: "সাইফ রহমান",
    authorPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    category: "Career advice",
    readMin: 10,
    body: "ইউনিভার্সিটি ডিগ্রি foundational knowledge দেয়, কিন্তু job-readiness নয়। বুটক্যাম্প outcome-driven, কিন্তু long-term breadth নেই। সেরা option হচ্ছে — degree + bootcamp।",
    publishedAt: "2026-03-28",
  },
  {
    slug: "freelance-1000usd",
    titleBn: "Freelance এ মাসে $১০০০ — যা যা জানা দরকার",
    titleEn: "$1000/month freelance — what you need to know",
    excerpt: "Upwork-এ থাকা সফল ফ্রিল্যান্সাররা যা করছেন।",
    cover: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1600&q=80",
    author: "ইমরান খান",
    authorPhoto: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80",
    category: "Success stories",
    readMin: 7,
    body: "প্রথম $1000 অর্জন করতে ৬ মাস লাগে — গড় হিসাব। সঠিক niche, profile, এবং pitching strategy থাকলে সময় কমে আসে।",
    publishedAt: "2026-03-15",
  },
  {
    slug: "ai-jobs-bd",
    titleBn: "AI জব মার্কেট বাংলাদেশে ২০২৬",
    titleEn: "AI Job Market in Bangladesh 2026",
    excerpt: "GPT-যুগে বাংলাদেশের ML ইঞ্জিনিয়ারদের চাহিদা।",
    cover: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1600&q=80",
    author: "তাসনিম আক্তার",
    authorPhoto: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&q=80",
    category: "Tech trends",
    readMin: 9,
    body: "২০২৬-এ বাংলাদেশে AI/ML রোলে ৩০০+ ওপেনিং ছিল প্রতি মাসে। গড় বেতন ১.২ লাখ টাকা।",
    publishedAt: "2026-03-08",
  },
  {
    slug: "mir-sakib-story",
    titleBn: "মীর সাকিবের গল্প — গ্রাম থেকে Pathao",
    titleEn: "Mir Sakib's Story — From village to Pathao",
    excerpt: "যাত্রার এক ছাত্রের ৬ মাসের জার্নি।",
    cover: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=1600&q=80",
    author: "যাত্রা টিম",
    authorPhoto: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&q=80",
    category: "Success stories",
    readMin: 12,
    body: "কুমিল্লার গ্রাম থেকে ঢাকার Pathao অফিস। মীর সাকিবের পুরো যাত্রা।",
    publishedAt: "2026-02-22",
  },
];

export const COMPANY_LOGOS = [
  { name: "Pathao", logo: "https://logo.clearbit.com/pathao.com" },
  { name: "bKash", logo: "https://logo.clearbit.com/bkash.com" },
  { name: "Nagad", logo: "https://logo.clearbit.com/nagad.com.bd" },
  { name: "Brain Station 23", logo: "https://logo.clearbit.com/brainstation-23.com" },
  { name: "Tiger IT", logo: "https://logo.clearbit.com/tigerit.com" },
  { name: "Therap", logo: "https://logo.clearbit.com/therapservices.net" },
  { name: "REVE Systems", logo: "https://logo.clearbit.com/revesoft.com" },
  { name: "Banglalink", logo: "https://logo.clearbit.com/banglalink.net" },
  { name: "Robi", logo: "https://logo.clearbit.com/robi.com.bd" },
  { name: "Grameenphone", logo: "https://logo.clearbit.com/grameenphone.com" },
  { name: "Daraz", logo: "https://logo.clearbit.com/daraz.com" },
  { name: "Foodpanda", logo: "https://logo.clearbit.com/foodpanda.com" },
  { name: "Microsoft", logo: "https://logo.clearbit.com/microsoft.com" },
  { name: "Amazon", logo: "https://logo.clearbit.com/amazon.com" },
  { name: "Google", logo: "https://logo.clearbit.com/google.com" },
  { name: "Meta", logo: "https://logo.clearbit.com/meta.com" },
];

export const PRESS_LOGOS = [
  { name: "The Daily Star", logo: "https://logo.clearbit.com/thedailystar.net" },
  { name: "Prothom Alo", logo: "https://logo.clearbit.com/prothomalo.com" },
  { name: "TBS", logo: "https://logo.clearbit.com/tbsnews.net" },
  { name: "Bonik Barta", logo: "https://logo.clearbit.com/bonikbarta.net" },
  { name: "Channel i", logo: "https://logo.clearbit.com/channelionline.com" },
  { name: "Daily Sun", logo: "https://logo.clearbit.com/daily-sun.com" },
];

export const PAYMENT_PARTNERS = [
  { name: "bKash", logo: "https://logo.clearbit.com/bkash.com" },
  { name: "Nagad", logo: "https://logo.clearbit.com/nagad.com.bd" },
  { name: "Rocket", logo: "https://logo.clearbit.com/dutchbanglabank.com" },
  { name: "Visa", logo: "https://logo.clearbit.com/visa.com" },
  { name: "Mastercard", logo: "https://logo.clearbit.com/mastercard.com" },
  { name: "City Bank", logo: "https://logo.clearbit.com/thecitybank.com" },
  { name: "BRAC Bank", logo: "https://logo.clearbit.com/bracbank.com" },
  { name: "EBL", logo: "https://logo.clearbit.com/ebl.com.bd" },
];

export const FAQS = [
  {
    q: "বুটক্যাম্প আর সাধারণ অনলাইন কোর্সের মধ্যে পার্থক্য কী?",
    a: "সাধারণ অনলাইন কোর্স self-paced এবং recorded — আপনি একা বসে শেখেন। বুটক্যাম্প cohort-based — সবাই একসাথে এগোয়, লাইভ ক্লাস হয়, ১:১ মেন্টর থাকে, real projects-এ কাজ করেন এবং চাকরির গ্যারান্টি পান।",
  },
  {
    q: "আমার পূর্ব অভিজ্ঞতা না থাকলে কি ভর্তি হতে পারব?",
    a: "হ্যাঁ! আমাদের অধিকাংশ ছাত্র beginner হিসেবে শুরু করেছেন। তবে স্ক্রিনিং টেস্টে aptitude এবং English comprehension যাচাই করা হয়। মূল প্রয়োজন — শেখার আগ্রহ এবং ১৫-২০ ঘণ্টা সাপ্তাহিক commitment।",
  },
  {
    q: "সবগুলো ক্লাস কি লাইভ?",
    a: "হ্যাঁ, ৯৫% ক্লাস লাইভ — সপ্তাহে ৫ দিন, সন্ধ্যা ৭-১০ PM। সব ক্লাস রেকর্ড থাকে, ক্লাস মিস করলেও যেকোনো সময় দেখতে পারবেন।",
  },
  {
    q: "ক্লাস মিস করলে কি হবে?",
    a: "প্রতিটি লাইভ ক্লাস HD recording এ available থাকে। অফলাইন download করে ছবি দেখার সুবিধা আছে (low data এর জন্য)। কিন্তু ৮০% attendance maintain করতে হবে চাকরির গ্যারান্টি পেতে।",
  },
  {
    q: "চাকরি না পেলে কি সত্যিই টাকা ফেরত পাব?",
    a: "হ্যাঁ — শর্ত পূরণ করলে ১০০% টিউশন ফি ফেরত। শর্তাবলি: স্ক্রিনিং পাস → ৮০%+ attendance → সব assignments জমা → career service ব্যবহার → ৬ মাসে চাকরি না পেলে। বিস্তারিত শর্তাবলি দেখুন।",
  },
  {
    q: "EMI কিভাবে কাজ করে?",
    a: "আমাদের পার্টনার ব্যাংকগুলো (City Bank, BRAC Bank, EBL) ৬ অথবা ১২ মাসের EMI সাপোর্ট করে। ৬ মাসের EMI সুদমুক্ত। ১২ মাসের EMI-তে minimal interest। NID + bank statement লাগে আবেদনের জন্য।",
  },
  {
    q: "আমি ফুল-টাইম চাকরি করি — কি বুটক্যাম্প করতে পারব?",
    a: "হ্যাঁ! আমাদের সব ক্লাস সন্ধ্যা ৭-১০ PM-এ হয় — অফিস শেষে join করতে পারবেন। ৫০%+ ছাত্র ফুল-টাইম চাকরি করেন। সাপ্তাহিক ১৫-২০ ঘণ্টা commit করতে পারলে যথেষ্ট।",
  },
  {
    q: "সার্টিফিকেট কি প্রতিষ্ঠানে স্বীকৃত?",
    a: "যাত্রার সার্টিফিকেট BD-র শীর্ষ ১০০+ কোম্পানি (Pathao, bKash, BS23) চিনে। তবে actual বিশ্বস্ততা আসে আপনার portfolio এবং interview performance থেকে।",
  },
  {
    q: "রিমোট ক্লাস হবে নাকি ফিজিক্যাল?",
    a: "১০০% রিমোট লাইভ ক্লাস — Zoom এবং Google Meet ব্যবহার করি। তবে ঢাকায় আমাদের অফিস আছে — আপনি চাইলে in-person consultation নিতে পারেন।",
  },
  {
    q: "বুটক্যাম্প শেষ করার পরও কি সাপোর্ট পাব?",
    a: "হ্যাঁ। লাইফটাইম alumni network access। যেকোনো সময় career advice, mentor sessions (limited), এবং Discord community-তে support পাবেন। চাকরি change করতে চাইলেও placement help পাবেন।",
  },
];
